# Generated by Django 6.0.5 on 2026-09-06 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('PA', 'Parent'), ('CH', 'Child')], db_index=True, max_length=2)),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('SI', 'Single choice'), ('MU', 'Multiple choice')], default='SI', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['audience', 'is_active'], name='onboarding__audienc_a84877_idx')],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='onboarding.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_answers', to=settings.AUTH_USER_MODEL)),
                ('choices', models.ManyToManyField(related_name='answers', to='onboarding.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onboarding.question')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'child_name'], name='onboarding__user_id_3b4ef8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question', 'child_name'), name='unique_answer_per_question_child')],
            },
        ),
    ]
