# Generated by Django 6.0.5 on 2026-09-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='onboarding__audienc_a84877_idx',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='audience',
            new_name='onboard_type',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['onboard_type', 'is_active'], name='onboarding__onboard_3d8eeb_idx'),
        ),
    ]
