# Generated by Django 6.0.5 on 2026-09-06 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_remove_question_onboarding__audienc_a84877_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, default='', max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('relationship', models.CharField(blank=True, choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], default='', max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='child_profile_images/')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_answer_per_question_child',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='onboarding__user_id_3b4ef8_idx',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_answers', to='onboarding.child'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', 'child'], name='onboarding__user_id_8eddaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'child'), name='unique_answer_per_question_child'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='child_name',
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent'], name='onboarding__parent__129dca_idx'),
        ),
    ]
